[package]
name = "genetic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.24"
nalgebra = { version = "0.31.1", features = ["rand-no-std", "rand"] }
rand = "0.8.5"
rand_distr = "0.4.3"
